// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using epizza.Domain.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace epizza.Domain.Models
{
    public partial class epizzaHubDBContext
    {
        private IepizzaHubDBContextProcedures _procedures;

        public virtual IepizzaHubDBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new epizzaHubDBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IepizzaHubDBContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class epizzaHubDBContextProcedures : IepizzaHubDBContextProcedures
    {
        private readonly epizzaHubDBContext _context;

        public epizzaHubDBContextProcedures(epizzaHubDBContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_GetOrderDetailsResult>> sp_GetOrderDetailsAsync(string orderId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrderId",
                    Size = 100,
                    Value = orderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_GetOrderDetailsResult>("EXEC @returnValue = [dbo].[sp_GetOrderDetails] @OrderId = @OrderId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
