// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using epizza.Domain.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace epizza.Domain.Models
{
    public partial interface IepizzaHubDBContextProcedures
    {
        Task<List<sp_GetOrderDetailsResult>> sp_GetOrderDetailsAsync(string orderId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
