// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace epizza.Domain.Models
{
    public partial class sp_GetOrderDetailsResult
    {
        [StringLength(2147483647)]
        public string PaymentId { get; set; }
        [StringLength(2147483647)]
        public string Street { get; set; }
        [StringLength(2147483647)]
        public string ZipCode { get; set; }
        [StringLength(2147483647)]
        public string City { get; set; }
        public int ItemId { get; set; }
        [Column("UnitPrice", TypeName = "decimal(18,2)")]
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
    }
}
